/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f446xx.h"

uint16_t rx_buff[10], tx_buff[10] = {0};

void DMA1_Stream5_IRQHandler(void)
{
	while(SPI3->SR & SPI_SR_BSY);

	SPI3->CR1 &= ~SPI_CR1_SPE;

	SPI3->CR2 &= ~(SPI_CR2_RXDMAEN |
				   SPI_CR2_TXDMAEN);

	DMA1->LIFCR = DMA_LIFCR_CHTIF2 |
				  DMA_LIFCR_CTCIF2;

	DMA1->HIFCR = DMA_HIFCR_CHTIF5 |
				  DMA_HIFCR_CTCIF5;
}

void TIM8_TRG_COM_TIM14_IRQHandler(void)
{
	TIM14->SR = 0;
	static uint16_t t = 0;

	for(uint32_t i = 0;i<10;i++)
		tx_buff[i] = (i << 8) | t;

	t++;

	SPI3->CR2 |= SPI_CR2_RXDMAEN;

	DMA1_Stream2->CR |= DMA_SxCR_EN;
	DMA1_Stream5->CR |= DMA_SxCR_EN;

	SPI3->CR2 |= SPI_CR2_TXDMAEN;

	SPI3->CR1 |= SPI_CR1_SPE;
}

int main(void)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN |
					RCC_AHB1ENR_GPIODEN |
					RCC_AHB1ENR_GPIOAEN |
					RCC_AHB1ENR_DMA1EN;
	RCC->APB1ENR |= RCC_APB1ENR_SPI3EN;


	GPIOC->AFR[1] |= 6 << (10*4-32);
	GPIOC->AFR[1] |= 6 << (11*4-32);
	GPIOC->AFR[1] |= 6 << (12*4-32);
	GPIOA->AFR[0] |= 6 << (4*4);

	GPIOD->MODER |= 1 << 2*2;
	GPIOC->MODER |= 2 << 10*2 |
					2 << 11*2 |
					2 << 12*2;
	GPIOA->MODER |= 2 << 4*2;


	SPI3->CR1 = SPI_CR1_DFF |
				SPI_CR1_SSM |
				SPI_CR1_SSI |
				SPI_CR1_MSTR |
				SPI_CR1_BR_0 |
				SPI_CR1_BR_1;



	DMA1_Stream2->PAR = (uint32_t)&SPI3->DR;
	DMA1_Stream2->M0AR = (uint32_t)&rx_buff;
	DMA1_Stream2->NDTR = (uint32_t)10;

	DMA1_Stream2->CR = DMA_SxCR_MINC |
					   DMA_SxCR_PSIZE_0 |
					   DMA_SxCR_MSIZE_0;

	DMA1_Stream5->PAR = (uint32_t)&SPI3->DR;
	DMA1_Stream5->M0AR = (uint32_t)&tx_buff;
	DMA1_Stream5->NDTR = (uint32_t)10;

	DMA1_Stream5->CR = DMA_SxCR_MINC |
					   DMA_SxCR_DIR_0 |
					   DMA_SxCR_PSIZE_0 |
					   DMA_SxCR_TCIE |
					   DMA_SxCR_MSIZE_0;

	SPI3->CR2 = SPI_CR2_SSOE;

	NVIC_EnableIRQ(DMA1_Stream5_IRQn);

	RCC->APB1ENR |= RCC_APB1ENR_TIM14EN;

	TIM14->PSC = 16000000/10000 - 1;
	TIM14->ARR = 10000/1 - 1;
	TIM14->DIER = TIM_DIER_UIE;
	TIM14->CR1 = TIM_CR1_CEN;

	NVIC_EnableIRQ(TIM8_TRG_COM_TIM14_IRQn);







    /* Loop forever */
	for(;;);
}
